name: color_rgb_a
description: Deprecated. Now part of shared_theme. Represents a color in the red-green-blue scheme with an optional alpha component. Designed for use with both Flutter and CSS.
version: 0.0.1+1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/color_rgb_a

dependencies:

dev_dependencies:
  test: ^1.3.0

environment:
  sdk: ">=1.19.0 <3.0.0"